alter table public.regras_cobranca
  alter column valor type text;

alter table public.pedidos
  add column if not exists pago_em timestamp without time zone;

update public.pedidos
set pago_em = coalesce(atualizado_em, criado_em, data_criacao)
where status = 'CONCLUIDO'
  and pago_em is null;

create table if not exists public.promocoes (
  id integer generated by default as identity primary key,
  nome varchar(160) not null,
  descricao text,
  desconto numeric(10,2) not null default 0,
  ativo boolean not null default true,
  criado_em timestamp without time zone not null default now(),
  atualizado_em timestamp without time zone not null default now(),
  produto_id integer references public.produtos(produto_id) on delete set null,
  tipo varchar(20) not null default 'PROMOCAO',
  inicio_em date,
  fim_em date,
  imagem text
);

create table if not exists public.pedido_cobranca_meta (
  pedido_id uuid primary key references public.pedidos(pedido_id) on delete cascade,
  numero_pedido varchar(100) not null,
  telefone_cliente varchar(50),
  data_vencimento date not null,
  criado_em timestamp without time zone not null default now(),
  atualizado_em timestamp without time zone not null default now()
);

create table if not exists public.billing_routine_runs (
  run_id uuid primary key,
  executado_em timestamp without time zone not null,
  referencia_em date not null,
  regra_ativa boolean not null,
  elegiveis integer not null,
  processados integer not null,
  ignorados integer not null,
  itens jsonb not null default '[]'::jsonb
);

create table if not exists public.billing_charge_sends (
  send_id uuid primary key,
  pedido_id uuid not null references public.pedidos(pedido_id) on delete cascade,
  tipo_envio varchar(20) not null,
  status varchar(20) not null,
  canal varchar(20),
  mensagem text not null,
  data_envio timestamp without time zone not null default now(),
  erro text,
  criado_em timestamp without time zone not null default now()
);

create index if not exists idx_promocoes_produto_id
  on public.promocoes(produto_id);

create index if not exists idx_pedido_cobranca_meta_data_vencimento
  on public.pedido_cobranca_meta(data_vencimento);

create index if not exists idx_billing_charge_sends_pedido_data
  on public.billing_charge_sends(pedido_id, data_envio desc);
