import { pool } from "../../config/database.js";
import type { AuthAdministrator, AuthRepository, BootstrapAdministratorInput } from "../auth.repository.js";

type AdministratorRow = {
  admin_id: number;
  nome: string;
  login: string;
  senha: string;
  permissao: string;
};

export class PostgresAuthRepository implements AuthRepository {
  private schemaReadyPromise?: Promise<void>;

  async ensureBootstrapAdministrator(input: BootstrapAdministratorInput): Promise<void> {
    await this.ensureSchema();
    const existing = await this.findByLogin(input.login);

    if (existing) {
      return;
    }

    await pool.query(
      `
        INSERT INTO administrators (nome, login, senha, permissao, criado_em)
        VALUES ($1, $2, $3, $4, NOW())
      `,
      [input.nome, input.login, input.senhaHash, input.permissao],
    );
  }

  async findByLogin(login: string): Promise<AuthAdministrator | null> {
    await this.ensureSchema();

    const result = await pool.query<AdministratorRow>(
      `
        SELECT admin_id, nome, login, senha, permissao
        FROM administrators
        WHERE lower(login) = lower($1)
        LIMIT 1
      `,
      [login],
    );

    const row = result.rows[0];
    return row
      ? {
          id: Number(row.admin_id),
          nome: row.nome,
          login: row.login,
          senha: row.senha,
          permissao: row.permissao,
        }
      : null;
  }

  private async ensureSchema(): Promise<void> {
    if (!this.schemaReadyPromise) {
      this.schemaReadyPromise = this.loadSchema();
    }

    await this.schemaReadyPromise;
  }

  private async loadSchema(): Promise<void> {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS administrators (
        admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(120) NOT NULL,
        login VARCHAR(160) NOT NULL,
        senha VARCHAR(255) NOT NULL,
        permissao VARCHAR(60) NOT NULL DEFAULT 'ADMIN',
        criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
      )
    `);

    await pool.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS administrators_login_unique_idx ON administrators ((lower(login)))`,
    );
  }
}
