export const API_ENDPOINTS = {
  login: "/auth/login",
  dashboardSummary: "/dashboard/summary",
  produtos: "/products",
  promotions: "/promotions",
  leads: "/leads",
  metricas: "/metrics",
  billingRules: "/billing-rules",
  billingOrders: "/billing-rules/orders",
  billingRuns: "/billing-rules/runs",
  billingChargeSend: (chargeId: number) => `/billing/charges/${chargeId}/send`,
  conversations: "/conversations",
  conversationMessages: (conversationId: number) => `/conversations/${conversationId}/messages`,
  conversationFullHistory: (conversationId: number) => `/conversations/${conversationId}/full-history`,
  conversationPrevious: (conversationId: number) => `/conversations/${conversationId}/previous`,
  conversationSendMessage: (conversationId: number) => `/conversations/${conversationId}/messages`,
  conversationStatus: (conversationId: number) => `/conversations/${conversationId}/status`,
} as const;
